name: Check team rules

on:
  push:
    paths:
      - .github/workflows/check-team-rules.yml
      
  workflow_dispatch:
      
jobs:
  check-code-owners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            console.log(`hello world`)

            github-token: ${{ secrets.GH_TOKEN }}

            const owner = context.repo.owner
            const repo = context.repo.repo
            const branch = "main"

            const rules = await github.rest.repos.getBranchProtection({
              owner,
              repo,
              branch,
            });

            console.log(`Rules:`)
            console.log(JSON.stringify(rules))
