name: Check team rules

on:
  push:
    paths:
      - .github/workflows/check-team-rules.yml
      
  workflow_dispatch:
      
jobs:
  check-code-owners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            console.log(`hello world`)

            const owner = context.repo.owner
            const repo = context.repo.repo
            const branch = "main"

            let rules
            try 
            {
              rules = await github.rest.repos.getBranchProtection({
                owner,
                repo,
                branch,
              });
            }
            catch {
              console.log(`No branch protection rules available`)
            }

            if (rules) {
              console.log(`Rules:`)
              console.log(JSON.stringify(rules))

              foreach (rule in rules) {
                // check if rule has the correct settings:
              }
            }

